name = "domain-hunter"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "DOMAIN_CACHE"
id = "bf0673cf5c8549009b78d8834cda81de"
preview_id = "94fa28d927ec4e2fbd1c4c206e9aae1b"
